meta_product_name: "Plus You"
meta_title: "Plus You - Product tagline"
meta_description: "No excuses to be at home without anything to do. Check our events and find new friends or volunteer for those who need company."
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
